/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vending.machine;

import javax.swing.JOptionPane;

/**
 *
 * @author Sara
 */
public class Vending extends javax.swing.JFrame {

    /**
     * Creates new form Vending
     */
    public Vending() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Jpanel = new javax.swing.JPanel();
        Coca = new javax.swing.JRadioButton();
        Pepsi = new javax.swing.JRadioButton();
        Sprite = new javax.swing.JRadioButton();
        Water = new javax.swing.JRadioButton();
        Lemond = new javax.swing.JRadioButton();
        Chocolate = new javax.swing.JRadioButton();
        Milk = new javax.swing.JRadioButton();
        Strawberry = new javax.swing.JRadioButton();
        Coffee = new javax.swing.JRadioButton();
        OKbtn = new javax.swing.JButton();
        Clearbtn = new javax.swing.JButton();
        Canclebtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        MilkTea = new javax.swing.JRadioButton();
        Yogurt = new javax.swing.JRadioButton();
        Ricemilk = new javax.swing.JRadioButton();
        Ginger = new javax.swing.JRadioButton();
        RootBeer = new javax.swing.JRadioButton();
        FantaOrange = new javax.swing.JRadioButton();
        FantaGrape = new javax.swing.JRadioButton();
        CreamSoda = new javax.swing.JRadioButton();
        RedBull = new javax.swing.JRadioButton();
        AlmondMilk = new javax.swing.JRadioButton();
        Monster = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        moneyTF = new javax.swing.JTextField();
        change = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 0));
        setForeground(java.awt.Color.pink);

        jLabel1.setBackground(new java.awt.Color(255, 51, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Vending Machine ");

        Jpanel.setBackground(new java.awt.Color(246, 36, 89));
        Jpanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Please select item", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18))); // NOI18N

        Coca.setBackground(new java.awt.Color(224, 130, 131));
        Coca.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Coca.setText("Coca Cola");
        Coca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CocaActionPerformed(evt);
            }
        });

        Pepsi.setBackground(new java.awt.Color(224, 130, 131));
        Pepsi.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Pepsi.setText("Pepsi");
        Pepsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PepsiActionPerformed(evt);
            }
        });

        Sprite.setBackground(new java.awt.Color(224, 130, 131));
        Sprite.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Sprite.setText("Sprite ");
        Sprite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpriteActionPerformed(evt);
            }
        });

        Water.setBackground(new java.awt.Color(224, 130, 131));
        Water.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Water.setText("Mineral Water");
        Water.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WaterActionPerformed(evt);
            }
        });

        Lemond.setBackground(new java.awt.Color(224, 130, 131));
        Lemond.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Lemond.setText("Lemond Tea");
        Lemond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LemondActionPerformed(evt);
            }
        });

        Chocolate.setBackground(new java.awt.Color(224, 130, 131));
        Chocolate.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Chocolate.setText("Chocolate Milk");
        Chocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChocolateActionPerformed(evt);
            }
        });

        Milk.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Milk.setText("Milk");
        Milk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MilkActionPerformed(evt);
            }
        });

        Strawberry.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Strawberry.setText("Strawberry Milk");
        Strawberry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StrawberryActionPerformed(evt);
            }
        });

        Coffee.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Coffee.setText("Coffee");
        Coffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoffeeActionPerformed(evt);
            }
        });

        OKbtn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        OKbtn.setText("OK");
        OKbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKbtnActionPerformed(evt);
            }
        });

        Clearbtn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        Clearbtn.setText("Clear");
        Clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearbtnActionPerformed(evt);
            }
        });

        Canclebtn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        Canclebtn.setText("Cancle");
        Canclebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CanclebtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("2 RM");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("2 RM");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("2 RM");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("1 RM");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("2 RM");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("3 RM");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("3 RM");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("3 RM");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("3 RM");

        MilkTea.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        MilkTea.setText("Milk Tea");
        MilkTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MilkTeaActionPerformed(evt);
            }
        });

        Yogurt.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Yogurt.setText("Yogurt");
        Yogurt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YogurtActionPerformed(evt);
            }
        });

        Ricemilk.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Ricemilk.setText("Rice Milk");
        Ricemilk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RicemilkActionPerformed(evt);
            }
        });

        Ginger.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Ginger.setText("Ginger Tea");
        Ginger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GingerActionPerformed(evt);
            }
        });

        RootBeer.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        RootBeer.setText("Root Beer");
        RootBeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RootBeerActionPerformed(evt);
            }
        });

        FantaOrange.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        FantaOrange.setText("Fanta Orange");
        FantaOrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FantaOrangeActionPerformed(evt);
            }
        });

        FantaGrape.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        FantaGrape.setText("Fanta Grape");
        FantaGrape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FantaGrapeActionPerformed(evt);
            }
        });

        CreamSoda.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        CreamSoda.setText("Cream Soda");
        CreamSoda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreamSodaActionPerformed(evt);
            }
        });

        RedBull.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        RedBull.setText("Red bull");
        RedBull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RedBullActionPerformed(evt);
            }
        });

        AlmondMilk.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        AlmondMilk.setText("Almond Milk");
        AlmondMilk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlmondMilkActionPerformed(evt);
            }
        });

        Monster.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Monster.setText("Monster");
        Monster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonsterActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("3 RM");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("3 RM");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("3 RM");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("2 RM");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("4 RM");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("3 RM");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("2 RM");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("2 RM");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("2 RM");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("3 RM");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("4 RM");

        javax.swing.GroupLayout JpanelLayout = new javax.swing.GroupLayout(Jpanel);
        Jpanel.setLayout(JpanelLayout);
        JpanelLayout.setHorizontalGroup(
            JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelLayout.createSequentialGroup()
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpanelLayout.createSequentialGroup()
                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(AlmondMilk))
                            .addGroup(JpanelLayout.createSequentialGroup()
                                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JpanelLayout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Coca)
                                            .addComponent(Milk)
                                            .addComponent(Ginger)
                                            .addGroup(JpanelLayout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addComponent(jLabel2))))
                                    .addGroup(JpanelLayout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(jLabel29)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpanelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JpanelLayout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(Pepsi))
                                    .addGroup(JpanelLayout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addComponent(jLabel3)))
                                .addGap(85, 85, 85)
                                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Sprite)
                                    .addGroup(JpanelLayout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel4)))
                                .addGap(105, 105, 105)
                                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Water)
                                    .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5)
                                        .addComponent(MilkTea)))
                                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JpanelLayout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Chocolate)
                                            .addGroup(JpanelLayout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addComponent(jLabel6)))
                                        .addGap(38, 38, 38)
                                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(JpanelLayout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addComponent(jLabel7))
                                            .addComponent(Lemond))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpanelLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RedBull)
                                            .addComponent(Ricemilk))
                                        .addGap(53, 53, 53))))
                            .addGroup(JpanelLayout.createSequentialGroup()
                                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(JpanelLayout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addComponent(jLabel10)
                                        .addGap(161, 161, 161)
                                        .addComponent(jLabel9)
                                        .addGap(109, 109, 109)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel16))
                                    .addGroup(JpanelLayout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Strawberry)
                                            .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Monster)
                                                .addComponent(RootBeer)))
                                        .addGap(84, 84, 84)
                                        .addComponent(FantaGrape)
                                        .addGap(127, 127, 127)
                                        .addComponent(CreamSoda)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(JpanelLayout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 588, Short.MAX_VALUE)
                                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpanelLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel21)
                                        .addGap(84, 84, 84))
                                    .addGroup(JpanelLayout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(38, 38, 38)
                                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Clearbtn)
                                            .addComponent(Canclebtn)
                                            .addComponent(OKbtn))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(JpanelLayout.createSequentialGroup()
                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(JpanelLayout.createSequentialGroup()
                                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JpanelLayout.createSequentialGroup()
                                        .addGap(65, 65, 65)
                                        .addComponent(jLabel8))
                                    .addGroup(JpanelLayout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(JpanelLayout.createSequentialGroup()
                                                    .addComponent(jLabel19)
                                                    .addGap(105, 105, 105)
                                                    .addComponent(jLabel20))
                                                .addGroup(JpanelLayout.createSequentialGroup()
                                                    .addGap(352, 352, 352)
                                                    .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel25)
                                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addComponent(Coffee)
                                            .addComponent(FantaOrange))))
                                .addGap(203, 203, 203)
                                .addComponent(Yogurt))
                            .addGroup(JpanelLayout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jLabel22)
                                .addGap(156, 156, 156)
                                .addComponent(jLabel23)
                                .addGap(135, 135, 135)
                                .addComponent(jLabel26)
                                .addGap(207, 207, 207)
                                .addComponent(jLabel27)
                                .addGap(44, 44, 44)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel28)
                        .addGap(91, 91, 91)))
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        JpanelLayout.setVerticalGroup(
            JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpanelLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpanelLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(329, 329, 329)))
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(JpanelLayout.createSequentialGroup()
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpanelLayout.createSequentialGroup()
                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpanelLayout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Pepsi)
                                    .addComponent(Sprite)
                                    .addComponent(Water)
                                    .addComponent(Chocolate)
                                    .addComponent(Lemond))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)))
                            .addGroup(JpanelLayout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(Coca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)))
                        .addGap(105, 105, 105)
                        .addComponent(Milk)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addGroup(JpanelLayout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Strawberry)
                            .addComponent(Coffee)
                            .addComponent(MilkTea)
                            .addComponent(Yogurt)
                            .addComponent(Ricemilk))
                        .addGap(18, 18, 18)
                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel21))))
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpanelLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(Ginger))
                    .addGroup(JpanelLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RootBeer)
                            .addComponent(FantaGrape)
                            .addComponent(CreamSoda)
                            .addComponent(RedBull))))
                .addGap(18, 18, 18)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JpanelLayout.createSequentialGroup()
                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpanelLayout.createSequentialGroup()
                                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel27))
                                .addGap(158, 158, 158)
                                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AlmondMilk)
                                    .addComponent(Monster)
                                    .addComponent(FantaOrange)))
                            .addComponent(jLabel22))
                        .addGap(24, 24, 24))
                    .addGroup(JpanelLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(OKbtn)
                        .addGap(46, 46, 46)))
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(Clearbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(Canclebtn)
                .addGap(255, 255, 255))
        );

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel11.setText("Insert Money:");

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel12.setText("Change :");

        moneyTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moneyTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel12)))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(moneyTF)
                            .addComponent(change, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(moneyTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(change, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(Jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel11.getAccessibleContext().setAccessibleName("Insert Money :");
        jLabel12.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CanclebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CanclebtnActionPerformed
        // cancle action
        int YesOrNo;
        YesOrNo = JOptionPane.showConfirmDialog(null,"Do you want to cancle your payment?","Dear Customer",JOptionPane.YES_NO_OPTION);
        if(YesOrNo == 0)
        {
         System.exit(0);
        }
       
        
    }//GEN-LAST:event_CanclebtnActionPerformed

    private void ClearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearbtnActionPerformed
        //clear action 
        Sprite.setSelected(false);
        Coca.setSelected(false);
        Pepsi.setSelected(false);
        Water.setSelected(false);
        Lemond.setSelected(false);
        Chocolate.setSelected(false);
        Milk.setSelected(false);
        Strawberry.setSelected(false);
        Coffee.setSelected(false);
        MilkTea.setSelected(false);
        Yogurt.setSelected(false);
        Ricemilk.setSelected(false);
        Ginger.setSelected(false);
        RootBeer.setSelected(false);
        FantaGrape.setSelected(false);
        CreamSoda.setSelected(false);
        AlmondMilk.setSelected(false);
        Monster.setSelected(false);
        FantaOrange.setSelected(false);
        RedBull.setSelected(false);
        moneyTF.setText(" ");
        change.setText(" ");
    }//GEN-LAST:event_ClearbtnActionPerformed

    private void CocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CocaActionPerformed
        // change radio to slect one
        if (Coca.isSelected()){
            Sprite.setSelected(false);
             Pepsi.setSelected(false);
            Water.setSelected(false);
            Lemond.setSelected(false);
            Chocolate.setSelected(false);
            Milk.setSelected(false);
            Strawberry.setSelected(false);
            Coffee.setSelected(false);
            MilkTea.setSelected(false);
            Yogurt.setSelected(false);
            Ricemilk.setSelected(false);
            Ginger.setSelected(false);
            RootBeer.setSelected(false);
            FantaGrape.setSelected(false);
            CreamSoda.setSelected(false);
            AlmondMilk.setSelected(false);
            Monster.setSelected(false);
            FantaOrange.setSelected(false);
            RedBull.setSelected(false);
        }
    }//GEN-LAST:event_CocaActionPerformed

    private void PepsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PepsiActionPerformed
       if(Pepsi.isSelected()){
           Sprite.setSelected(false);
           Coca.setSelected(false);
            Water.setSelected(false);
            Lemond.setSelected(false);
            Chocolate.setSelected(false);
            Milk.setSelected(false);
            Strawberry.setSelected(false);
            Coffee.setSelected(false);
            MilkTea.setSelected(false);
            Yogurt.setSelected(false);
            Ricemilk.setSelected(false);
            Ginger.setSelected(false);
            RootBeer.setSelected(false);
            FantaGrape.setSelected(false);
            CreamSoda.setSelected(false);
            AlmondMilk.setSelected(false);
            Monster.setSelected(false);
            FantaOrange.setSelected(false);
            RedBull.setSelected(false);
       }
    }//GEN-LAST:event_PepsiActionPerformed

    private void SpriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpriteActionPerformed
        if(Sprite.isSelected()){
           Pepsi.setSelected(false);
           Coca.setSelected(false);
            Water.setSelected(false);
            Lemond.setSelected(false);
            Chocolate.setSelected(false);
            Milk.setSelected(false);
            Strawberry.setSelected(false);
            Coffee.setSelected(false);
            MilkTea.setSelected(false);
            Yogurt.setSelected(false);
            Ricemilk.setSelected(false);
            Ginger.setSelected(false);
            RootBeer.setSelected(false);
            FantaGrape.setSelected(false);
            CreamSoda.setSelected(false);
            AlmondMilk.setSelected(false);
            Monster.setSelected(false);
            FantaOrange.setSelected(false);
            RedBull.setSelected(false);
        }
    }//GEN-LAST:event_SpriteActionPerformed

    private void WaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WaterActionPerformed
      if(Water.isSelected()){
           Pepsi.setSelected(false);
           Coca.setSelected(false);
            Sprite.setSelected(false);
            Lemond.setSelected(false);
            Chocolate.setSelected(false);
            Milk.setSelected(false);
            Strawberry.setSelected(false);
            Coffee.setSelected(false);
            MilkTea.setSelected(false);
            Yogurt.setSelected(false);
            Ricemilk.setSelected(false);
            Ginger.setSelected(false);
            RootBeer.setSelected(false);
            FantaGrape.setSelected(false);
            CreamSoda.setSelected(false);
            AlmondMilk.setSelected(false);
            Monster.setSelected(false);
            FantaOrange.setSelected(false);
            RedBull.setSelected(false);
          }
    }//GEN-LAST:event_WaterActionPerformed

    private void LemondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LemondActionPerformed
        if(Lemond.isSelected()){
             Pepsi.setSelected(false);
           Coca.setSelected(false);
            Sprite.setSelected(false);
            Water.setSelected(false);
            Chocolate.setSelected(false);
            Milk.setSelected(false);
            Strawberry.setSelected(false);
            Coffee.setSelected(false);
        }
    }//GEN-LAST:event_LemondActionPerformed

    private void ChocolateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChocolateActionPerformed
       if(Chocolate.isSelected()){
             Pepsi.setSelected(false);
           Coca.setSelected(false);
            Sprite.setSelected(false);
            Water.setSelected(false);
            Lemond.setSelected(false);
            Milk.setSelected(false);
            Strawberry.setSelected(false);
            Coffee.setSelected(false);
            MilkTea.setSelected(false);
            Yogurt.setSelected(false);
            Ricemilk.setSelected(false);
            Ginger.setSelected(false);
            RootBeer.setSelected(false);
            FantaGrape.setSelected(false);
            CreamSoda.setSelected(false);
            AlmondMilk.setSelected(false);
            Monster.setSelected(false);
            FantaOrange.setSelected(false);
            RedBull.setSelected(false);
       }
    }//GEN-LAST:event_ChocolateActionPerformed

    private void MilkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MilkActionPerformed
        if(Milk.isSelected()){
             Pepsi.setSelected(false);
           Coca.setSelected(false);
            Sprite.setSelected(false);
            Water.setSelected(false);
            Lemond.setSelected(false);
            Chocolate.setSelected(false);
            Strawberry.setSelected(false);
            Coffee.setSelected(false); 
            MilkTea.setSelected(false);
            Yogurt.setSelected(false);
            Ricemilk.setSelected(false);
            Ginger.setSelected(false);
            RootBeer.setSelected(false);
            FantaGrape.setSelected(false);
            CreamSoda.setSelected(false);
            AlmondMilk.setSelected(false);
            Monster.setSelected(false);
            FantaOrange.setSelected(false);
            RedBull.setSelected(false);
        }
    }//GEN-LAST:event_MilkActionPerformed

    private void StrawberryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StrawberryActionPerformed
       if(Strawberry.isSelected()){
              Pepsi.setSelected(false);
           Coca.setSelected(false);
            Sprite.setSelected(false);
            Water.setSelected(false);
            Lemond.setSelected(false);
            Chocolate.setSelected(false);
            Milk.setSelected(false);
            Coffee.setSelected(false); 
            MilkTea.setSelected(false);
            Yogurt.setSelected(false);
            Ricemilk.setSelected(false);
            Ginger.setSelected(false);
            RootBeer.setSelected(false);
            FantaGrape.setSelected(false);
            CreamSoda.setSelected(false);
            AlmondMilk.setSelected(false);
            Monster.setSelected(false);
            FantaOrange.setSelected(false);
            RedBull.setSelected(false);
           }
    }//GEN-LAST:event_StrawberryActionPerformed

    private void CoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoffeeActionPerformed
       if(Coffee.isSelected()){
              Pepsi.setSelected(false);
           Coca.setSelected(false);
            Sprite.setSelected(false);
            Water.setSelected(false);
            Lemond.setSelected(false);
            Chocolate.setSelected(false);
            Milk.setSelected(false);
            Strawberry.setSelected(false); 
            MilkTea.setSelected(false);
            Yogurt.setSelected(false);
            Ricemilk.setSelected(false);
            Ginger.setSelected(false);
            RootBeer.setSelected(false);
            FantaGrape.setSelected(false);
            CreamSoda.setSelected(false);
            AlmondMilk.setSelected(false);
            Monster.setSelected(false);
            FantaOrange.setSelected(false);
            RedBull.setSelected(false);
       }
    }//GEN-LAST:event_CoffeeActionPerformed

    private void moneyTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moneyTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moneyTFActionPerformed

    private void OKbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKbtnActionPerformed
        // pay for purchase if enough of money 
        
        double money = 0; 
        
        money = Double.parseDouble(moneyTF.getText());
        if (Coca.isSelected()){
            money = money - 2;
            
        }else if (Pepsi.isSelected()){
            money = money - 2;
           
        }else if (Sprite.isSelected()){
            money = money - 2;
        }else if (Water.isSelected()){
            money = money - 1;
        }else if (Lemond.isSelected()){
            money = money - 2;
        }else if (Chocolate.isSelected()){
            money = money - 3;
        }else if (Milk.isSelected()){
            money = money - 3;
        }else if (Strawberry.isSelected()){
            money = money - 3;
        }else if (Coffee.isSelected()){
            money = money - 3;
        }else if (MilkTea.isSelected()){
            money = money - 3;
        }else if (Yogurt.isSelected()){
            money = money - 3;
        }else if(Ricemilk.isSelected()){
            money = money - 3;
        }else if (Ginger.isSelected()){
            money = money - 2;
        }else if (RootBeer.isSelected()){
            money = money - 4;
        }else if (FantaGrape.isSelected()){
            money = money - 2;
        }else if (CreamSoda.isSelected()){
            money = money - 2;
        }else if(AlmondMilk.isSelected()){
            money = money - 4;
        }else if(Monster.isSelected()){
            money = money - 3;
        }else if(FantaOrange.isSelected()){
            money = money - 2;
        }else if(RedBull.isSelected()){
            money = money - 3;
        }
        
          if (money < 0){
              JOptionPane.showMessageDialog(rootPane, "Do Not Have Enough Of Money" );
          } else {
              change.setText(Double.toString(money));
          }
    }//GEN-LAST:event_OKbtnActionPerformed

    private void MilkTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MilkTeaActionPerformed
        if(MilkTea.isSelected()){
              Pepsi.setSelected(false);
           Coca.setSelected(false);
            Sprite.setSelected(false);
            Water.setSelected(false);
            Lemond.setSelected(false);
            Chocolate.setSelected(false);
            Milk.setSelected(false);
            Strawberry.setSelected(false); 
            Coffee.setSelected(false);
            Yogurt.setSelected(false);
            Ricemilk.setSelected(false);
            Ginger.setSelected(false);
            RootBeer.setSelected(false);
            FantaGrape.setSelected(false);
            CreamSoda.setSelected(false);
            AlmondMilk.setSelected(false);
            Monster.setSelected(false);
            FantaOrange.setSelected(false);
            RedBull.setSelected(false);
       }
    }//GEN-LAST:event_MilkTeaActionPerformed

    private void YogurtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YogurtActionPerformed
       if(Yogurt.isSelected()){
              Pepsi.setSelected(false);
           Coca.setSelected(false);
            Sprite.setSelected(false);
            Water.setSelected(false);
            Lemond.setSelected(false);
            Chocolate.setSelected(false);
            Milk.setSelected(false);
            Strawberry.setSelected(false); 
            MilkTea.setSelected(false);
            Coffee.setSelected(false);
            Ricemilk.setSelected(false);
            Ginger.setSelected(false);
            RootBeer.setSelected(false);
            FantaGrape.setSelected(false);
            CreamSoda.setSelected(false);
            AlmondMilk.setSelected(false);
            Monster.setSelected(false);
            FantaOrange.setSelected(false);
            RedBull.setSelected(false);
       }
    }//GEN-LAST:event_YogurtActionPerformed

    private void RicemilkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RicemilkActionPerformed
       if(Ricemilk.isSelected()){
              Pepsi.setSelected(false);
           Coca.setSelected(false);
            Sprite.setSelected(false);
            Water.setSelected(false);
            Lemond.setSelected(false);
            Chocolate.setSelected(false);
            Milk.setSelected(false);
            Strawberry.setSelected(false); 
            MilkTea.setSelected(false);
            Yogurt.setSelected(false);
            Coffee.setSelected(false);
            Ginger.setSelected(false);
            RootBeer.setSelected(false);
            FantaGrape.setSelected(false);
            CreamSoda.setSelected(false);
            AlmondMilk.setSelected(false);
            Monster.setSelected(false);
            FantaOrange.setSelected(false);
            RedBull.setSelected(false);
       }
    }//GEN-LAST:event_RicemilkActionPerformed

    private void GingerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GingerActionPerformed
        if(Ginger.isSelected()){
              Pepsi.setSelected(false);
           Coca.setSelected(false);
            Sprite.setSelected(false);
            Water.setSelected(false);
            Lemond.setSelected(false);
            Chocolate.setSelected(false);
            Milk.setSelected(false);
            Strawberry.setSelected(false); 
            MilkTea.setSelected(false);
            Yogurt.setSelected(false);
            Ricemilk.setSelected(false);
            Coffee.setSelected(false);
            RootBeer.setSelected(false);
            FantaGrape.setSelected(false);
            CreamSoda.setSelected(false);
            AlmondMilk.setSelected(false);
            Monster.setSelected(false);
            FantaOrange.setSelected(false);
            RedBull.setSelected(false);
       }
    }//GEN-LAST:event_GingerActionPerformed

    private void RootBeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RootBeerActionPerformed
        if(RootBeer.isSelected()){
              Pepsi.setSelected(false);
           Coca.setSelected(false);
            Sprite.setSelected(false);
            Water.setSelected(false);
            Lemond.setSelected(false);
            Chocolate.setSelected(false);
            Milk.setSelected(false);
            Strawberry.setSelected(false); 
            MilkTea.setSelected(false);
            Yogurt.setSelected(false);
            Ricemilk.setSelected(false);
            Ginger.setSelected(false);
            Coffee.setSelected(false);
            FantaGrape.setSelected(false);
            CreamSoda.setSelected(false);
            AlmondMilk.setSelected(false);
            Monster.setSelected(false);
            FantaOrange.setSelected(false);
            RedBull.setSelected(false);
       }
    }//GEN-LAST:event_RootBeerActionPerformed

    private void FantaGrapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FantaGrapeActionPerformed
        if(FantaGrape.isSelected()){
              Pepsi.setSelected(false);
           Coca.setSelected(false);
            Sprite.setSelected(false);
            Water.setSelected(false);
            Lemond.setSelected(false);
            Chocolate.setSelected(false);
            Milk.setSelected(false);
            Strawberry.setSelected(false); 
            MilkTea.setSelected(false);
            Yogurt.setSelected(false);
            Ricemilk.setSelected(false);
            Ginger.setSelected(false);
            RootBeer.setSelected(false);
            Coffee.setSelected(false);
            CreamSoda.setSelected(false);
            AlmondMilk.setSelected(false);
            Monster.setSelected(false);
            FantaOrange.setSelected(false);
            RedBull.setSelected(false);
       }
    }//GEN-LAST:event_FantaGrapeActionPerformed

    private void CreamSodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreamSodaActionPerformed
     if(CreamSoda.isSelected()){
              Pepsi.setSelected(false);
           Coca.setSelected(false);
            Sprite.setSelected(false);
            Water.setSelected(false);
            Lemond.setSelected(false);
            Chocolate.setSelected(false);
            Milk.setSelected(false);
            Strawberry.setSelected(false); 
            MilkTea.setSelected(false);
            Yogurt.setSelected(false);
            Ricemilk.setSelected(false);
            Ginger.setSelected(false);
            RootBeer.setSelected(false);
            FantaGrape.setSelected(false);
            Coffee.setSelected(false);
            AlmondMilk.setSelected(false);
            Monster.setSelected(false);
            FantaOrange.setSelected(false);
            RedBull.setSelected(false);
       }
    }//GEN-LAST:event_CreamSodaActionPerformed

    private void AlmondMilkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlmondMilkActionPerformed
        if(AlmondMilk.isSelected()){
              Pepsi.setSelected(false);
           Coca.setSelected(false);
            Sprite.setSelected(false);
            Water.setSelected(false);
            Lemond.setSelected(false);
            Chocolate.setSelected(false);
            Milk.setSelected(false);
            Strawberry.setSelected(false); 
            MilkTea.setSelected(false);
            Yogurt.setSelected(false);
            Ricemilk.setSelected(false);
            Ginger.setSelected(false);
            RootBeer.setSelected(false);
            FantaGrape.setSelected(false);
            CreamSoda.setSelected(false);
            Coffee.setSelected(false);
            Monster.setSelected(false);
            FantaOrange.setSelected(false);
            RedBull.setSelected(false);
       }
    }//GEN-LAST:event_AlmondMilkActionPerformed

    private void MonsterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonsterActionPerformed
        if(Monster.isSelected()){
              Pepsi.setSelected(false);
           Coca.setSelected(false);
            Sprite.setSelected(false);
            Water.setSelected(false);
            Lemond.setSelected(false);
            Chocolate.setSelected(false);
            Milk.setSelected(false);
            Strawberry.setSelected(false); 
            MilkTea.setSelected(false);
            Yogurt.setSelected(false);
            Ricemilk.setSelected(false);
            Ginger.setSelected(false);
            RootBeer.setSelected(false);
            FantaGrape.setSelected(false);
            CreamSoda.setSelected(false);
            AlmondMilk.setSelected(false);
            Coffee.setSelected(false);
            FantaOrange.setSelected(false);
            RedBull.setSelected(false);
       }
    }//GEN-LAST:event_MonsterActionPerformed

    private void FantaOrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FantaOrangeActionPerformed
        if(FantaOrange.isSelected()){
              Pepsi.setSelected(false);
           Coca.setSelected(false);
            Sprite.setSelected(false);
            Water.setSelected(false);
            Lemond.setSelected(false);
            Chocolate.setSelected(false);
            Milk.setSelected(false);
            Strawberry.setSelected(false); 
            MilkTea.setSelected(false);
            Yogurt.setSelected(false);
            Ricemilk.setSelected(false);
            Ginger.setSelected(false);
            RootBeer.setSelected(false);
            FantaGrape.setSelected(false);
            CreamSoda.setSelected(false);
            AlmondMilk.setSelected(false);
            Monster.setSelected(false);
            Coffee.setSelected(false);
            RedBull.setSelected(false);
       }
    }//GEN-LAST:event_FantaOrangeActionPerformed

    private void RedBullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RedBullActionPerformed
        if(RedBull.isSelected()){
              Pepsi.setSelected(false);
           Coca.setSelected(false);
            Sprite.setSelected(false);
            Water.setSelected(false);
            Lemond.setSelected(false);
            Chocolate.setSelected(false);
            Milk.setSelected(false);
            Strawberry.setSelected(false); 
            MilkTea.setSelected(false);
            Yogurt.setSelected(false);
            Ricemilk.setSelected(false);
            Ginger.setSelected(false);
            RootBeer.setSelected(false);
            FantaGrape.setSelected(false);
            CreamSoda.setSelected(false);
            AlmondMilk.setSelected(false);
            Monster.setSelected(false);
            FantaOrange.setSelected(false);
            Coffee.setSelected(false);
       }
    }//GEN-LAST:event_RedBullActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vending.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vending.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vending.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vending.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vending().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AlmondMilk;
    private javax.swing.JButton Canclebtn;
    private javax.swing.JRadioButton Chocolate;
    private javax.swing.JButton Clearbtn;
    private javax.swing.JRadioButton Coca;
    private javax.swing.JRadioButton Coffee;
    private javax.swing.JRadioButton CreamSoda;
    private javax.swing.JRadioButton FantaGrape;
    private javax.swing.JRadioButton FantaOrange;
    private javax.swing.JRadioButton Ginger;
    private javax.swing.JPanel Jpanel;
    private javax.swing.JRadioButton Lemond;
    private javax.swing.JRadioButton Milk;
    private javax.swing.JRadioButton MilkTea;
    private javax.swing.JRadioButton Monster;
    private javax.swing.JButton OKbtn;
    private javax.swing.JRadioButton Pepsi;
    private javax.swing.JRadioButton RedBull;
    private javax.swing.JRadioButton Ricemilk;
    private javax.swing.JRadioButton RootBeer;
    private javax.swing.JRadioButton Sprite;
    private javax.swing.JRadioButton Strawberry;
    private javax.swing.JRadioButton Water;
    private javax.swing.JRadioButton Yogurt;
    private javax.swing.JTextField change;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField moneyTF;
    // End of variables declaration//GEN-END:variables
}
